dist: trusty
sudo: off
language: python
services:
  - docker
git:
  depth: false
addons:
  apt:
    packages:
      - libssl-dev
      - libffi-dev
      - python-dev
install: pip install tox
cache: pip
jobs:
  include:
    - stage: verify
      env:
      - PURPOSE='Automation'
      - REDUCE_SDK='True'
      script: ./scripts/ci/test_automation.sh
      python: 3.6
stages:
  - verify